### ISSUE TITLE
Create pedestal table using online-dt-corrected data

### ISSUE THREAD

**Issue by SeiyaNozaki** [cta-observatory/cta-lstchain#1014]
It would be nice to have an option to create pedestal table using data to which dt correction is already applied by EVB. 

Now dt correction is always applied in this tool (hard-coded), so I think what we need to change is just adding an argument input to switch off dt correction in this tool.

**Comment by DirkHoffmann** [comment]
Can you produce a dummy or unity table, which applies the neutral operations ("×1 +0") as pedestal/calibration table. Then you can use it (wasting a bit of computing power, indeed) instead of a real table and have the same effect as "switching off corrections".

**Comment by maxnoe** [comment]
Back from vacation now.

We should just remove the hard coded option in the lstchain tool and allow it to be configurable as intended.

> Can you produce a dummy or unity table, which applies the neutral operations ("×1 +0") as pedestal/calibration table.

Not currently, no. The factor is hardcoded in `ctapipe_io_lst` (which is something bothering me since a long time!) and it can only be switched on and off. And lstchain happens to switch it on in `lstchain_create_pedestal_file` (that's actually my fault).


Let me note that we still need a way to tell which corrections have been applied by EVB from inside the file, either in the events or in the camera configuration object.

There is a field `pre_proc_algorithms` in the `CameraConfiguration` which is at the moment always 0 and @DirkHoffmann told me some reason I cannot remember right now why that wouldn't be appropriate and we need a data model change.

However, I insist that any information on this is better than having to know from run books which which settings a run was taken.

```
CameraConfiguration(
    telescope_id=1
    cs_serial='FGZZLD2\n'
    configuration_id=3669
    date=1613414546
    num_pixels=1848
    num_samples=40
    expected_pixels_id=array([1731, 1638, ..., 1767, 1686], dtype=uint16)
    data_model_version='1.0'
    nectarcam=NectarCamConfig(
        idaq_version=''
        cdhs_version=''
        acquisition_mode=0
        num_modules=0
        expected_modules_id=array([], dtype=float64)
        algorithms=0
        run_id=0)
    lstcam=LstCamConfig(
        idaq_version='40790'
        cdhs_version=''
        num_modules=264
        expected_modules_id=array([ 89,  90, ..., 174, 175], dtype=uint16)
        algorithms=0
        pre_proc_algorithms=0
        run_id=3669)
    digicam=DigiCamConfig(
        ))
```

**Comment by maxnoe** [comment]
Command line option added to the tool in #1016
