### ISSUE TITLE
DRS4 baseline script does not exit after critical error messages

### ISSUE THREAD

**Issue by marialainez** [cta-observatory/cta-lstchain#1181]
When running the onsite_create_drs4_pedestal_file script, sometimes CRITICAL error messages are found, but the exit code is 0 and it finishes apparently OK. This happens for example for the data taken on 2023/11/10 (taken with EvB v6), since with the new data format the DRS4 offset is always immediately applied: 

```
2023-11-20 10:06:59,803 CRITICAL [lstchain.lstchain_create_drs4_pedestal_file] (lstchain_create_drs4_pedestal_file.finish): 8726424 baseline values are smaller than 0
2023-11-20 10:07:26,152 WARNING [lstchain.lstchain_create_drs4_pedestal_file] (lstchain_create_drs4_pedestal_file.finish): 15196159 baseline values are smaller than 25
```

**Comment by maxnoe** [comment]
This was discussed at the time... It's not an error condition on the computation of DRS4 baseline values. 

It's supposed to warn the experts that the settings of the DRS4 chips should probably be adjusted. I was opposed to calling it "CRITICAL" since that as you commented implies that something actually failed.

**Comment by maxnoe** [comment]
Side note: that you are seeing this on the EVBv6 data is a different issue and we need to adjust.

I am opening an issue for this, as discussed via email.
