### ISSUE TITLE
Only one offset bin when creating IRF with diffuse mc and energy dependant theta cut

### ISSUE THREAD

**Issue by mdebony** [cta-observatory/cta-lstchain#1322]
When creating IRFs with the script lstchain_create_irf_files.py using a gamma diffuse MC file and energy dependent theta cut, the produced IRFs contained only one large offset bin without regards for the setting provided in the configuration file.

I think the issue come from this part of the code :
https://github.com/cta-observatory/cta-lstchain/blob/9aaa78b0bd911d35fc2b3fefa03b064bb21b8262/lstchain/tools/lstchain_create_irf_files.py#L467C1-L480C18

I could propose a fix if you want.

**Comment by moralejo** [comment]
Thanks for raising this, and great if you can propose a fix.
 
Related to it: how are the Ereco-dependent cuts determined when diffuse gamma MC is used? Are the efficiencies computed with all gammas, regardless of the offset angle? Probably it is better to limit the offset, so that the target efficiency is achieved near the center of the FoV. 

And another question: when Ereco-dependent theta cuts are requested, are the Aeff and migration matrix, in each offset bin, computed with the **theta** cut already applied?  If the answer is yes for the mig matrix, this will only work well for pointlike sources. If it is no, it will be sub-optimal for pointlike sources (worse E-resolution than the one we really have after the theta cut). As for Aeff, is it the total one (only gammaness cut, not theta), to be later scaled, using the psf, depending on the theta cut?

**Comment by maxnoe** [comment]
> And another question: when Ereco-dependent theta cuts are requested, are the Aeff and migration matrix, in each offset bin, computed with the theta cut already applied? 

They must be, that's the definition of point-like IRFs.

**Comment by mdebony** [comment]
I will check all of those points to be sure everything is done as expected.

> Related to it: how are the Ereco-dependent cuts determined when diffuse gamma MC is used? Are the efficiencies computed with all gammas, regardless of the offset angle? Probably it is better to limit the offset, so that the target efficiency is achieved near the center of the FoV.
A possibility would be to limit to the maximum offset used in the configuration file for the irfs.

**Comment by moralejo** [comment]
> > And another question: when Ereco-dependent theta cuts are requested, are the Aeff and migration matrix, in each offset bin, computed with the theta cut already applied?
> 
> They must be, that's the definition of point-like IRFs.

Right, thanks, silly question...  I was mixing up full-enclosure with having "full-FoV" IRF, which is obviously not the same. With the E-reco dependent cuts and diffuse MC as input we will have point-like IRFs in bins of offset angle, i.e. for the full FoV.  But valid only for analysis of pointlike sources.
