### ISSUE TITLE
gain selection with Monte Carlo

### ISSUE THREAD

**Issue by yrenier** [cta-observatory/cta-lstchain#411]
Hello,
the default gain selection threshold used for data is way too large when using simulations.
The main problem is that `LSTCameraCalibrator._calibrate_dl1()` is looking at the waveforms in r1 which are very different for data and MC:
- on data: waveforms in r1 are in LSB units, and the saturation arise around 4000 LSB (12 bit ADC) consistent with the default configuration: `config['gain_selector_config']['threshold']=3500`
- on simulation:  waveforms in r1 are in pe units. In my simulations the high gain is 40 and the factor between the integrated charge and the pulse amplitude is \~5 wich means the threshold should be \~200 times smaller than the default value. I found that  `config['gain_selector_config']['threshold']=16` gives reasonable results in my case.

**Comment by MaxNoe** [comment]
I I understood the discussions about data levels and calibration correctly, the issue is the other way around.

R1 should be already in units of p.e. for observed data, not different on MCs

**Comment by vuillaut** [comment]
Hi @yrenier 
Yes R1 should be in p.e. already (MC and real data).
Unfortunately, there was a bug in gain selection in ctapipe v0.7.0 (corrected) that was applying the threshold in p.e. (R1) rather than in ADC (R0).
At the moment, this issue is handled:
- for real data, with custom gain selection (done during the real data calibration)
- for MC, with a threshold at ~20p.e. (you have to change the threshold yourself)
 
This issue has been discussed internally for LST1 and will be corrected with the next release of ctapipe. Thank you for reporting it openly here if you are using lstchain with other data.

**Comment by rlopezcoto** [comment]
https://github.com/cta-observatory/cta-lstchain/issues/197
