### ISSUE TITLE
Weird change of dl1ab script output

### ISSUE THREAD

**Issue by moralejo** [cta-observatory/cta-lstchain#846]
After merging #841 I tried the dl1ab script on an MC file and noticed two strange things:
- size of output is more than twice than it was with the previous version. This is probably related to compression level, which was 5 before bt default and is now 0
- the source_filenames group is missing (note that I also merged #844)

**Comment by maxnoe** [comment]
> size of output is more than twice than it was with the previous version. This is probably related to compression level, which was 5 before bt default and is now 0

That is strange, since I didn't change the way the output file is opened:

Filters are given:
```
with open_file(output_filename, 'w', filters=filters) as merge_file:
```

**Comment by maxnoe** [comment]
Ah, damn, but it changed in `dl1ab`, will fix

**Comment by Bultako** [comment]
`source_filenames` group is now missing because the `auto_merge_h5files` function has been replaced by `copy_h5_nodes` in `lstchain/scripts/lstchain_dl1ab.py` after merging  PR #841 

See diffs below:

https://github.com/cta-observatory/cta-lstchain/pull/841/files#diff-3a347ffbf2140ae48c8fb9e556ee26242315b730b8b28411f48fee526cae6eb6L31

https://github.com/cta-observatory/cta-lstchain/pull/841/files#diff-3a347ffbf2140ae48c8fb9e556ee26242315b730b8b28411f48fee526cae6eb6L183

https://github.com/cta-observatory/cta-lstchain/pull/841/files#diff-3a347ffbf2140ae48c8fb9e556ee26242315b730b8b28411f48fee526cae6eb6R205

If we want to continue considering `lstchain/scripts/lstchain_dl1ab.py` script as merging of files we should recover  `auto_merge_h5files` function, but I don't think it is the case, it is more a transformation than a merging.

**Comment by maxnoe** [comment]
Will fix both

**Comment by Bultako** [comment]
ok
if we want to keep track of the previous file before transformation (it's a sensible use case for provenance tracking) we should also fix this.
